language: r
os:
  - linux
  - osx 
r:
  - oldrel
  - release
  - devel
cache: packages

r_check_args: --as-cran --run-donttest --no-build-vignettes --no-manual

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'